//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDiagnosisAndCategory
    {
        public int Member_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Most_Severe_Diagnosis_ID { get; set; }
        public string Most_Severe_Diagnosis_Description { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Category_Description { get; set; }
        public Nullable<int> Category_Score { get; set; }
        public string Is_Most_Severe_Category { get; set; }
    }
}
